name: build-packages
on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  pull_request:
    types: [closed]
env:
  DEBFULLNAME: Brokenpip3
  DEBEMAIL: brokenpip3@gmail.com
jobs:
  bats-support-assert:
    name: build bats-support and assert
    runs-on: ubuntu-latest
    env:
      SUPPORT-TAG: 0.3.0
      ASSERT-TAG: 2.0.0
    steps:
      - name: Install prerequisites
        run: sudo apt install dh-make devscripts -y

      - name: Bats-support - Checkout upstream
        uses: actions/checkout@v2
        with:
          repository: bats-core/bats-support
          path: bats-support-${{ env.SUPPORT-TAG }}-1
          ref: v${{ env.SUPPORT-TAG }}
      - name: Bats-support - Checkout debian
        uses: actions/checkout@v2
        with:
          path: bats-support-debian
      - name: Bats-support - dh_make
        working-directory: bats-support-${{ env.SUPPORT-TAG }}-1
        run: dh_make --createorig -s -y
      - name: Bats-support - Override defaults
        working-directory: bats-support-${{ env.SUPPORT-TAG }}-1
        run: cp ../bats-support-debian/bats-support/* debian/
      - name: Bats-support - debuild
        working-directory: bats-support-${{ env.SUPPORT-TAG }}-1
        run: debuild -us -uc
      - name: Bats-support - install
        working-directory: bats-support-${{ env.SUPPORT-TAG }}-1
        run: sudo apt install -y ../bats-support-${{ env.SUPPORT-TAG }}*.deb
      - name: Bats-support - make test
        working-directory: bats-support-${{ env.SUPPORT-TAG }}-1
        run: bats /usr/lib/bats-support/test/

      - name: Bats-assert - Checkout upstream
        uses: actions/checkout@v2
        with:
          repository: bats-core/bats-assert
          path: bats-assert-${{ env.ASSERT-TAG }}-1
          ref: v${{ env.ASSERT-TAG }}
      - name: Bats-assert - Checkout debian
        uses: actions/checkout@v2
        with:
          path: bats-assert-debian
      - name: Bats-assert - dh_make
        working-directory: bats-assert-${{ env.ASSERT-TAG }}-1
        run: dh_make --createorig -s -y
      - name: Bats-assert - Override defaults
        working-directory: bats-assert-${{ env.ASSERT-TAG }}-1
        run: cp ../bats-assert-debian/bats-assert/* debian/
      - name: Bats-assert - debuild
        working-directory: bats-assert-${{ env.ASSERT-TAG }}-1
        run: debuild -us -uc
      - name: Bats-assert - install
        working-directory: bats-assert-${{ env.ASSERT-TAG }}-1
        run: sudo apt install -y ../bats-assert-${{ env.ASSERT-TAG }}*.deb
      - name: Bats-assert - make test
        working-directory: bats-assert-${{ env.ASSERT-TAG }}-1
        run: bats /usr/lib/bats-assert/test/

      - name: Bats-support and assert - upload deb
        uses: actions/upload-artifact@v2
        with:
          name: bats-support
          path: bats-support-${{ env.SUPPORT-TAG }}_1-1_amd64.deb

  make-release:
    needs: bats-support-assert
    name: relase and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bats-*.deb
