name: build-packages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    types: [closed]
jobs:
  bats-support:
    name: build bats-support
    runs-on: ubuntu-latest
    env:
      DEBFULLNAME: Brokenpip3
      DEBEMAIL: brokenpip3@gmail.com
      TAG: 0.3.0
    steps:
      - name: Bats-support - Checkout upstream
        uses: actions/checkout@v2
        with:
          repository: bats-core/bats-support
          path: bats-support-${{ env.TAG }}-1
          ref: v${{ env.TAG }}
      - name: Bats-support - Checkout debian
        uses: actions/checkout@v2
        with:
          path: bats-support-debian
      - name: Bats-support - install prerequisites
        run: sudo apt install dh-make devscripts -y
      - name: Bats-support - dh_make
        working-directory: bats-support-${{ env.TAG }}-1
        run: dh_make --createorig -s -y
      - name: Bats-support - Override defaults 
        working-directory: bats-support-${{ env.TAG }}-1
        run: cp ../bats-support-debian/bats-support/* debian/
      - name: Bats-support - Debug
        working-directory: bats-support-${{ env.TAG }}-1
        run: |
          printf "\n###\n\n"
          ls -lrt 
          printf "\n###\n\n"
          ls -lrt debian
          printf "\n###\n\n"
          ls -lrt ../
      - name: Bats-support - debuild
        working-directory: bats-support-${{ env.TAG }}-1
        run: debuild -us -uc
      - name: Bats-support - install
        working-directory: bats-support-${{ env.TAG }}-1
        run: sudo apt install -y ../bats-support-${{ env.TAG }}*.deb
      - name: Bats-support - make test
        working-directory: bats-support-${{ env.TAG }}-1
        run: bats /usr/lib/bats-assert/test/
